// https://simpleicons.org
export const TECH_BADGE_INFO: Record<string, { color: string; logo: string }> = {
  "HTML": { color: "E34F26", logo: "html5" },
  "CSS": { color: "1572B6", logo: "css" },
  "JavaScript": { color: "F7DF1E", logo: "javascript" },
  "TypeScript": { color: "3178C6", logo: "typescript" },
  "React": { color: "61DAFB", logo: "react" },
  "Next.js": { color: "000000", logo: "nextdotjs" },
  "Node.js": { color: "5FA04E", logo: "nodedotjs" },
  "Express": { color: "000000", logo: "express" },
  "Python": { color: "3776AB", logo: "python" },
  "Django": { color: "092E20", logo: "django" },
  "Flask": { color: "000000", logo: "flask" },
  "Java": { color: "007396", logo: "openjdk" },
  "Spring": { color: "6DB33F", logo: "spring" },
  "MariaDB": { color: "003545", logo: "mariadb" },
  "MongoDB": { color: "47A248", logo: "mongodb" },
  "Redis": { color: "FF4438", logo: "redis" },
  "Linux": { color: "FCC624", logo: "linux" },
  "Apache": { color: "D22128", logo: "apache" },
  "ApacheTomcat": { color: "F8DC75", logo: "apachetomcat" },
  "Nginx": { color: "009639", logo: "nginx" },
  "Docker": { color: "2496ED", logo: "docker" },
  "Vercel": { color: "000000", logo: "vercel" },
  "Websocket": { color: "010101", logo: "socketdotio" }, // 대체 가능 고유 로고
};